# Generated by Django 5.0.2 on 2025-01-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjiraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('motto', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('link', models.URLField()),
            ],
        ),
    ]
